### ISSUE TITLE
update z5 version

### ISSUE THREAD

**Issue by gdkrmr** [gdkrmr/zarr-R#1]
We are currently wrapping v1.5.1 of z5, v2 will be released at some point. z5 v1.5.1 only supports storage on local disk.

**Comment by constantinpape** [comment]
@gdkrmr I have just made a pre-release of 2.0.0. I will finalize the release once the conda build is working, but the new API should be fixed already.

Note that version 2.0.0 does not implement any cloud based storage yet, but the API supports multiple storage backends and I have started the s3 implementation already, but it's not working yet.

**Comment by gdkrmr** [comment]
I think the current version is working relatively well.
